# iris_cnn



In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
# from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dense, Conv1D, Flatten

In [0]:
!wget https://raw.githubusercontent.com/dhrim/hallym_medi_workshop_2020/master/material/iris_with_category_index.csv
  

--2020-02-15 14:28:26--  https://raw.githubusercontent.com/dhrim/hallym_medi_workshop_2020/master/material/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2218 (2.2K) [text/plain]
Saving to: ‘iris_with_category_index.csv’

iris_with_category_ 100%[===================>]   2.17K  --.-KB/s    in 0s      

2020-02-15 14:28:31 (45.3 MB/s) - ‘iris_with_category_index.csv’ saved [2218/2218]



In [0]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [0]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [0]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

train_x = np.reshape(train_x, (100, 4, 1))  # ADD
test_x = np.reshape(test_x, (20, 4, 1))     # ADD

print(train_x.shape)  # ADD
print(test_x.shape)   # ADD


(100, 4)
(100, 1)
(20, 4)
(20, 1)
(100, 4, 1)
(20, 4, 1)


In [0]:
model = keras.Sequential()
model.add(Conv1D(4, 3, activation='relu', input_shape=(4,1))) # ADD
model.add(Flatten())  # ADD
# model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu')) # modify
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax")) # 1이 아니고 클래스 수 3이다

model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)


Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 2, 4)              16        
_________________________________________________________________
flatten (Flatten)            (None, 8)                 0         
_________________________________________________________________
dense (Dense)                (None, 10)                90        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 249
Trainable params: 249
Non-trainable params: 0
_________________________________________________________________
20/20 [==============================] - 0s

In [0]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.97899175e-01 2.10075825e-03 5.75631773e-12]
 [4.93423780e-03 9.94462907e-01 6.02790620e-04]
 [9.87706006e-01 1.22939702e-02 9.66763114e-10]
 [2.28394245e-04 9.98270869e-01 1.50079816e-03]
 [9.98650730e-01 1.34933344e-03 2.33505121e-12]
 [9.99311328e-01 6.88632310e-04 2.41106045e-13]
 [9.99622464e-01 3.77471995e-04 4.90324774e-14]
 [9.99575913e-01 4.24130500e-04 1.11333414e-13]
 [8.65180697e-03 9.91216779e-01 1.31454712e-04]
 [9.96255279e-01 3.74473375e-03 1.47887171e-11]
 [3.79898052e-06 2.32887849e-01 7.67108321e-01]
 [2.65125011e-04 9.94480729e-01 5.25421416e-03]
 [9.95629430e-01 4.37055575e-03 1.63043225e-11]
 [1.26147413e-07 2.01344714e-02 9.79865372e-01]
 [9.98938262e-01 1.06174080e-03 2.41921153e-12]
 [2.33983010e-05 8.32126498e-01 1.67850077e-01]
 [2.48962053e-04 9.97147858e-01 2.60325172e-03]
 [9.96331155e-01 3.66886449e-03 4.00881828e-11]
 [9.97829139e-01 2.17084517e-03 5.34186107e-12]
 [8.23668845e-04 9.98099506e-01 1.07680389e-03]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 